#! /usr/bin/env bash

##################################
#                                #
#     Run script created by      #
#     Jippe Heijnen              #
#     (C) 2019                   #
#                                #
##################################

if [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo "Linux detected, continuing";
fi

cd ~/iPass/test/iPass_test>/dev/null;sudo make clean>/dev/null;sudo make build
if cat /proc/version | grep "Microsoft"; then
	echo "!WSL DETECTED!";
	cmd.exe /c @mode com5:1200
	DEVICE=ttyS5
	sudo bossac -p $DEVICE -U false -e -w -b main.bin -R || sudo bossac -p ttyACM1 -U false -e -w -b main.bin -R
else
	echo "Not wsl, great!";
	DEVICE=ttyACM0
	sudo stty -F /dev/$DEVICE speed 1200 cs8 -cstopb -parenb || sudo stty -F /dev/ttyACM1 speed 1200 cs8 -cstopb -parenb 
	sudo bossac -p $DEVICE -U false -e -w -v -b main.bin -R || sudo bossac -p ttyACM1 -U false -e -w -v -b main.bin -R
fi

